### ISSUE TITLE
cookbook: recipe for a loading screen

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/webxdc_docs#10]
using that setUpdateListener returns a promise: https://github.com/deltachat/deltachat-core-rust/issues/3203

maybe structured like that:
- why should you want a loading screen? normally you might show your state instantly, but it might not be efficient to replay the previous states visible to the user, or you might want to block interaction with the webxdc until all previous states are replayed
- see also caching with localstorage (needs  also an tutorial page), though that does not help with first open (when others already created many updates or when opening for the first time on a different device as localstorage is not synced.)
- simple example
- explain the example?

**Comment by hpk42** [comment]
nobody working on this for a year, closing.

**Comment by Simon-Laux** [comment]
I think it still makes sense to have some examples for newbies
