### ISSUE TITLE
Ambiguities that could be resolved

### ISSUE THREAD

**Issue by rosano** [webxdc/webxdc_docs#21]
- `update.info` or `update.summary` and any time 'one line of text' is shown, a character limit could be specified
- the icon's "reasonable width/height" could be defined specifically and optionally min/max dimensions.
- there is a TODO on the tips and tricks page
- webxdc capitalization is inconsistent between webxdc, Webxdc. I would pick one or use WebXDC/webXDC so that it's visually more legible and screenreaders will pronounce properly

**Comment by WofWca** [comment]
FYI in the web world they capitalize such names: https://developer.mozilla.org/en-US/docs/Web/API
E.g. WebRTC, WebUSB, WebOTP.
