### ISSUE TITLE
write "development on android" guide

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/webxdc_docs#3]
Try developing an Webxdc app on android to write the guide (https://github.com/deltachat/webxdc_docs/blob/master/src/02_02_02_dev_tool_android.md)

Termux might be too intimidating for beginners, so maybe create a small helper app that allows to create webxdc projects and more:

- create projects, using the simulator repo (https://github.com/deltachat/webxdc-dev) as template
- start the project in a http server that injects eruda.js as console to debug on mobile
- package the webxdc project into a `.xdc` file
- Optionale buttons to open the project dir in installed apps (via intent):
   - an editor app like acode
   - local filemanager
   - termux
- the app could also have an offline version of the [docs](https://github.com/deltachat/webxdc_docs) packaged in it.

**Comment by hpk42** [comment]
i don't quite understand this 18 months issue, and the links are partly dead.  
I guess it's better to put this to the forum if it's still a viable suggestion.

**Comment by Simon-Laux** [comment]
> i don't quite understand this 18 months issue

basically a tutorial/guide for people that have no computer and are just developing on their (android) smartphone.
@adbenitez recently saw that someone attempted making a plugin for an android code editor, maybe we should rather look into that to improve the guides for the "I have no computer" case.
