### ISSUE TITLE
Access to user avatars?

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc_docs#35]
We now have [`selfName`](https://github.com/webxdc/webxdc_docs/blob/eadf86b383722f78da6a8fe465e7b0cfefe07fa6/src/spec.md?plain=1#L94) and `selfAddr`.
I thought that avatars would also make sense.

I remember we talked about replacing `selfName` and `selfAddr` with some faceless UUIDs. I think it needs to be reconsidered.

**Comment by Simon-Laux** [comment]
> I remember we talked about replacing selfName and selfAddr with some faceless UUIDs. I think it needs to be reconsidered.

replacing email address makes sense, also we should provide sender information with each update outside of the payload (put there by core):
```json
{
payload:{...},
author: { id: local contact id hashed together with chat id, displayname: string}
}
```

For avatars we can then have a virtual directory inside of the webxdc that serves the avatar pictures:
```
/webxdc-avatars/{author.id}.jpg
```

**Comment by singpolyma** [comment]
Avatars and display names can both change over time.  It might make sense to have a `webxdc.getUserProfile(author.id)` call that can return relevant display name / virtual path / anything else

**Comment by WofWca** [comment]
Moved to https://support.delta.chat/t/webxdc-selfavatar-access-to-user-avatars/2734?u=wofwca
