### ISSUE TITLE
Does `setUpdateListener` remove the previously set listener?

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc_docs#39]
I think the spec needs to clarify this.

And if it does remove it, how does it relate to the `Promise` returned by `setUpdateListener`? I.e. if we synchronously call `setUpdateListener` two times in a row, does the first `Promise` never resolve? Should it act like `.onclick = `?

**Comment by Simon-Laux** [comment]
you should ever only call it once, it replaces the listener and I would say the returned promise is undefined behavior when calling it multiple times.

**Comment by WofWca** [comment]
> you should ever only call it once

Now the question is - once per what? Can you call it again after a navigation (`location.assign('/page2.html')`)

**Comment by Simon-Laux** [comment]
I think it replaces the previous listener on all implementations
