### ISSUE TITLE
warn against using local storage for much data

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/webxdc_docs#56]
localstorage has a limit depending on the browser its 4-10mb, which you can fill up with your json objects if not careful.
https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values/

IndexedDB https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API is an alternative you can use that has less limitations. Maybe the webxdc spec will also offer some data store in the future that could be managed by the application or deltachat-core

**Comment by adbenitez** [comment]
this is important wrt app-store bot, where we plan to cache downloaded apps: https://github.com/webxdc/appstore-bot/pull/76
