### ISSUE TITLE
Other things that don't work ("Discouraged practices")

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc_docs#66]
We have some documented here https://docs.webxdc.org/spec.html#discouraged-practises , but here are some other ones:
- Things that require secure context don't work on Desktop(e.g. Geolocation, Device Orientation, Web Crypto API), see
  - https://support.delta.chat/t/allow-access-to-camera-geolocation-other-web-apis/2446?u=wofwca
  - https://github.com/webxdc/webxdc-test/pull/24
- Things that require a permission (e.g. camera, microphone, Geolocation) don't work. These things mostly (or all of them) require secure context as well, see above forum post link.
  - Desktop: https://github.com/deltachat/deltachat-desktop/blob/f5f073a8f6c98082cb131bc8eef774c5edaadc7d/src/main/deltachat/webxdc.ts#L396-L423
  - Android: I believe the Delta Chat app itself would require the permissions that it wants to grant to the apps.
- I believe the fact that [we run in the app in an `<iframe>`](https://github.com/deltachat/deltachat-desktop/blob/b46b770dbf41dda1406bfa775beae2c6fe2a604a/static/webxdc_wrapper.html#L33-L34) might cause permission-related problems, see e.g. the [`allow` attribute of `<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attributes), but I can't name an example.
- `window.open` 95% doesn't work, you can't open new windows. `window.open('/page2.html', '_self')` does work like `location.assign('/page2.html)`
  On Desktop it's because of [`setWindowOpenHandler`](https://github.com/deltachat/deltachat-desktop/blob/853b584251a5dacf60ebc616f7fb10edffb5c5e5/src/main/index.ts#L270-L273), on Android I think [this](https://github.com/deltachat/deltachat-android/blob/3f581caa8c1fc52128030d65734850438bafb51f/src/org/thoughtcrime/securesms/WebxdcActivity.java#L206) is the responsible code, judging from @webratte 's messages in the "webxdc devs" group.
- `globalThis.prompt()` doesn't work on Desktop, see https://github.com/electron/electron/issues/472
- Obviously, [the CSP](https://github.com/deltachat/deltachat-desktop/blob/f5f073a8f6c98082cb131bc8eef774c5edaadc7d/src/main/deltachat/webxdc.ts#L42-L50) is pretty restrictive, but I'm not sure if it's just "no access to the Internet" or something more.
- ~~`beforeunload`'s prompt (something live "you have unsaved changes, do you want to leave the page?") doesn't work in Delta Chat desktop, see~~
  It's already documented.
  - ~~https://github.com/deltachat/deltachat-desktop/issues/3321#issuecomment-1645325910~~
  - ~~https://codeberg.org/webxdc/editor/issues/12#issuecomment-990799~~

**Comment by r10s** [comment]
> Things that require secure context don't work on Desktop(e.g. Geolocation, Device Orientation, Web Crypto API)

at least crypto.randomUUID() seems to work on all platforms (used in calendar)
