### ISSUE TITLE
`importFiles()`: `mimeType` description is confusing

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc_docs#67]
https://github.com/webxdc/webxdc_docs/blob/d49439d7af77b82bb138ce3f8d7ad854437a4642/src/spec.md?plain=1#L155-L162

- Does `mimeType` filter out files that are left after the `extensions` filter? Or does it add extra on top?
- Does it only apply to files with no extension?

#55 recently changed it.

**Comment by r10s** [comment]
i think, this is clear enough now. if not, please open a PR directly
