### ISSUE TITLE
More granular navigation and page structure

### ISSUE THREAD

**Issue by ansuz** [webxdc/webxdc_docs#79]
Some of the chapters in the docs are quite long, particularly the _Webxdc Specification_ and _Tips & Tricks_. I propose that we split them up into subchapters. I think this would make the mdbook easier to navigate overall, and it might also improve results in search engines.

The mdbook docs provide [an example](https://rust-lang.github.io/mdBook/format/summary.html#example) of how to structure `SUMMARY.md` with a nested structure to achieve this layout.

If such a change would be welcome I'll submit a PR to migrate to the new structure.

**Comment by WofWca** [comment]
TBH I think it doesn't really matter, so I'm fine with it.
One thing to keep in mind is that some people prefer the docs to be on a signle page for easier search, like, say, https://lodash.com/. But there is a "search" function in mdBook. But not all people are aware of it.

**Comment by hpk42** [comment]
#80 was refined and now merged, so we have a more granular structure now. thanks @ansuz
