### ISSUE TITLE
trouble shooting entry for platform specific viewport scaling / zoom

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/webxdc_docs#8]
see https://github.com/deltachat/deltachat-core-rust/pull/3214

**Comment by hpk42** [comment]
i re-read this core issue a number of times but am not sure what you are suggesting specifically. 
Closing because not actionable.  As you know more than me (and many others) about the topic i suggest that either you or @r10s or so create a PR in tips_and_tricks.md , thanks.
